export const MemberItem = [
  {
    imageSrc: '/assets/InterviewOta.png',
    imageAlt: 'InterviewOta',
    message1: '新規事業企画を経て、',
    message2: 'プロモーション戦略を担当。',
    name: 'Y.O',
    hireYear: '2021',
    position: 'AWSチーム チーフエンジニア',
  },
  {
    imageSrc: '/assets/InterviewWang.png',
    imageAlt: 'InterviewWang',
    message1: '新規事業企画を経て、',
    message2: 'プロモーション戦略を担当。',
    name: 'C.W',
    hireYear: '2022',
    position: 'フロントエンドエンジニア',
  },
  {
    imageSrc: '/assets/InterviewMoroda.png',
    imageAlt: 'InterviewMoroda',
    message1: '新規事業企画を経て、',
    message2: 'プロモーション戦略を担当。',
    name: 'T.M',
    hireYear: '20XX',
    position: 'iOSアプリエンジニア',
  },
  {
    imageSrc: '/assets/InterviewChacon.png',
    imageAlt: 'InterviewChacon',
    message1: '新規事業企画を経て、',
    message2: 'プロモーション戦略を担当。',
    name: 'D.C',
    hireYear: '20XX',
    position: 'フルスタックエンジニア',
  },
  {
    imageSrc: '/assets/InterviewOu.png',
    imageAlt: 'InterviewOu',
    message1: '新規事業企画を経て、',
    message2: 'プロモーション戦略を担当。',
    name: 'K.O',
    hireYear: '2022',
    position: 'バックエンドエンジニア',
  },
];
