export const MemberIntroductions = [
  {
    imageSrc: '/assets/InterviewOta.png',
    imageAlt: 'Y.O/2021年入社 AWSチーム チーフエンジニア',
    message1: '新規事業企画を経て、',
    message2: 'プロモーション戦略を担当。',
    name: 'Y.O',
    hireYear: '2021',
    position: 'AWSチーム チーフエンジニア',
  },
  {
    imageSrc: '/assets/InterviewWang.png',
    imageAlt: 'C.W/2022年入社 フロントエンドエンジニア',
    message1: '新規事業企画を経て、',
    message2: 'プロモーション戦略を担当。',
    name: 'C.W',
    hireYear: '2022',
    position: 'フロントエンドエンジニア',
  },
  {
    imageSrc: '/assets/InterviewMoroda.png',
    imageAlt: 'T.M/20XX年入社 iOSアプリエンジニア',
    message1: '新規事業企画を経て、',
    message2: 'プロモーション戦略を担当。',
    name: 'T.M',
    hireYear: '20XX',
    position: 'iOSアプリエンジニア',
  },
  {
    imageSrc: '/assets/InterviewChacon.png',
    imageAlt: 'D.C/20XX年入社 フルスタックエンジニア',
    message1: '新規事業企画を経て、',
    message2: 'プロモーション戦略を担当。',
    name: 'D.C',
    hireYear: '20XX',
    position: 'フルスタックエンジニア',
  },
  {
    imageSrc: '/assets/InterviewOu.png',
    imageAlt: 'K.O/2022年入社 バックエンドエンジニア',
    message1: '新規事業企画を経て、',
    message2: 'プロモーション戦略を担当。',
    name: 'K.O',
    hireYear: '2022',
    position: 'バックエンドエンジニア',
  },
];
