name: Build

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  build:
    name: Build npm
    if: |
      github.event.pull_request.draft == false
      && !startsWith(github.head_ref, 'release')
      && !startsWith(github.head_ref, 'doc')
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: ./.github/actions/set-up-node
      - name: Run npm build
        run: npm run build
      - name: Format and lint using npm
        run: npm run format && npm run lint
